### ISSUE TITLE
Multiple assertion failed

### ISSUE THREAD

**Issue by JBG-brad** [centricular/webrtcsink#19]
When trying to run the demo project, everything works up until I actually try to load the stream.

Once I do, I get a series of GSTREAMER critical errors with assertions failed 

Console output:

```
(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.547: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.547: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.547: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:4058): WARNING **: 17:52:50.547: (../subprojects/gst-plugins-bad/ext/webrtc/transportreceivebin.c:348):transport_receive_bin_constructed: code should not be reached

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.547: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.547: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.547: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.547: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.548: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:4058): CRITICAL **: 17:52:50.548: gst_dtls_srtp_dec_request_new_pad: assertion 'self->bin.dtls_element' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.548: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.548: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.548: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:4058): WARNING **: 17:52:50.548: (../subprojects/gst-plugins-bad/ext/webrtc/gstwebrtcbin.c:2251):_create_transport_channel: code should not be reached

** (gst-launch-1.0:4058): WARNING **: 17:52:50.550: (../subprojects/gst-plugins-bad/ext/webrtc/gstwebrtcbin.c:2257):_create_transport_channel: code should not be reached

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_pad_get_peer: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_ref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_pad_add_probe: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_pad_get_peer: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_ref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_pad_add_probe: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_pad_get_peer: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_ref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_pad_add_probe: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.550: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:4058): CRITICAL **: 17:52:50.552: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed

** (gst-launch-1.0:4058): CRITICAL **: 17:52:50.552: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed
2022-01-27 17:52:50,584 - webrtc.signalling - INFO - Connection to peer ('10.18.27.150', 60873) closed, exiting handler
2022-01-27 17:52:50,584 - webrtc.signalling - INFO - Cleaned up ab22072a-cd81-4d99-a51d-ce2c90a6c702 -> 180596a6-b173-4868-8262-1f15752072cb session
2022-01-27 17:52:50,584 - webrtc.signalling - INFO - Disconnected from peer 'ab22072a-cd81-4d99-a51d-ce2c90a6c702' at ('10.18.27.150', 60873)

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.584: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.584: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:4058): GStreamer-CRITICAL **: 17:52:50.585: gst_object_unref: assertion 'object != NULL' failed
2022-01-27 17:53:47,213 - webrtc.signalling - INFO - Connection to peer ('10.18.27.150', 60731) closed, exiting handler
2022-01-27 17:53:47,213 - webrtc.signalling - INFO - Disconnected from peer 'c496fed8-df4e-4993-8ebb-3b9f32450d28' at ('10.18.27.150', 60731)
0:03:50.9 / 99:99:99.
```
Browser console:

```
webrtc.js:100 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=fingerprint:sha-256 (null) Failed to create fingerprint from the digest.
    at RTCPeerConnection.setRemoteDescription (https://webrtc.github.io/adapter/adapter-latest.js:1421:37)
    at Session.onIncomingSDP (http://10.18.27.10:8000/webrtc.js:131:30)
    at Session.onServerMessage (http://10.18.27.10:8000/webrtc.js:173:22)
```

Not quite sure what's happening here.

**Comment by MathieuDuponchelle** [comment]
GStreamer version ?

**Comment by JBG-brad** [comment]
Oh right, that'd be helpful.

gst-launch-1.0 version 1.19.3                                                   
GStreamer 1.19.3 (GIT)

I built from `main` as the README suggested.

**Comment by MathieuDuponchelle** [comment]
I see, thanks. Please collect a stacktrace and perhaps GST_DEBUG=2 logs. Also helpful would be to know what command you're running exactly :)

**Comment by JBG-brad** [comment]
This is everything I'm getting from logging.

I'm literally just running through the tutorial steps in the README.md trying to explore if this would be a good tool for an upcoming project.  Thanks for looking into this and sorry if I'm doing something stupid!

```
root@2b835082451c:/code/webrtcsink/www# gst-launch-1.0 webrtcsink signaller::address="ws://localhost:8443" name=ws videotestsrc ! ws. a
udiotestsrc ! ws.
0:00:00.034984246  6049 0x55ac7a97c780 WARN      GST_PLUGIN_LOADING gstplugin.c:505:gst_plugin_register_func: plugin "/code/webrtcsink/target/debug/deps/libwebrtcsink.so" has unknown license "MIT"
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
Redistribute latency...
0:00:00.046385288  6049 0x7f7b5c0618c0 WARN         audio-resampler audio-resampler.c:274:convert_taps_gint16_c: can't find exact taps
0:00:00.065639666  6049 0x7f7b5c061c00 WARN                  vpxenc gstvpxenc.c:1860:gst_vpx_enc_set_format:<vp9enc0> Failed to set VP8E_SET_NOISE_SENSITIVITY: incapable
0:00:00.065830317  6049 0x7f7b5c061c00 WARN                  vpxenc gstvpxenc.c:1880:gst_vpx_enc_set_format:<vp9enc0> Failed to set VP8E_SET_TOKEN_PARTIONS: incapable
2022-01-27 19:13:10,056 - webrtc.signalling - INFO - Connected to ('127.0.0.1', 60656)
2022-01-27 19:13:10,056 - webrtc.signalling - INFO - Registered peer 'c96f5450-6ebf-48fc-a5a7-7aebec485ee6' at ('127.0.0.1', 60656)
10.18.27.150 - - [27/Jan/2022 19:13:26] "GET / HTTP/1.1" 304 -
2022-01-27 19:13:26,696 - webrtc.signalling - INFO - Connection to peer ('10.18.27.150', 59770) closed, exiting handler
2022-01-27 19:13:26,697 - webrtc.signalling - INFO - Disconnected from peer '57b31585-40c3-45de-af0a-3d996dabe0c6' at ('10.18.27.150', 59770)
2022-01-27 19:13:26,716 - webrtc.signalling - INFO - Connected to ('10.18.27.150', 59929)
2022-01-27 19:13:26,721 - webrtc.signalling - INFO - Registered peer '18aecaa3-9e51-44d6-9459-377e2a01ed07' at ('10.18.27.150', 59929)
2022-01-27 19:13:28,819 - webrtc.signalling - INFO - Connected to ('10.18.27.150', 59936)
2022-01-27 19:13:28,830 - webrtc.signalling - INFO - Registered peer '79c2b726-8117-4e6e-9113-4ffcd36d5749' at ('10.18.27.150', 59936)
2022-01-27 19:13:28,836 - webrtc.signalling - INFO - '79c2b726-8117-4e6e-9113-4ffcd36d5749' command 'START_SESSION c96f5450-6ebf-48fc-a5a7-7aebec485ee6'
2022-01-27 19:13:28,836 - webrtc.signalling - INFO - Session from '79c2b726-8117-4e6e-9113-4ffcd36d5749' (('10.18.27.150', 59936)) to 'c96f5450-6ebf-48fc-a5a7-7aebec485ee6' (('127.0.0.1', 60656))
0:00:18.868663974  6049 0x7f7b480076a0 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:701:gst_element_factory_make_with_properties: no such element factory "srtpenc"!
0:00:18.868690596  6049 0x7f7b480076a0 ERROR            dtlssrtpenc gstdtlssrtpenc.c:210:gst_dtls_srtp_enc_init:<GstDtlsSrtpEnc@0x7f7b2c008020> failed to create srtp encoder, is the srtp plugin registered?

** (gst-launch-1.0:6049): WARNING **: 19:13:28.840: tried to set connection-id after disabling DTLS
0:00:18.868783417  6049 0x7f7b480076a0 WARN             dtlssrtpenc gstdtlssrtpenc.c:317:gst_dtls_srtp_enc_set_property:<dtlssrtpenc0> tried to set is-client after disabling DTLS
0:00:18.868836841  6049 0x7f7b480076a0 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:701:gst_element_factory_make_with_properties: no such element factory "srtpdec"!
0:00:18.868846031  6049 0x7f7b480076a0 ERROR            dtlssrtpdec gstdtlssrtpdec.c:190:gst_dtls_srtp_dec_init:<GstDtlsSrtpDec@0x7f7b2c00a040> failed to create srtp_dec, is the srtp plugin registered?

** (gst-launch-1.0:6049): WARNING **: 19:13:28.840: tried to set connection-id after disabling DTLS

** (gst-launch-1.0:6049): WARNING **: 19:13:28.841: (../subprojects/gst-plugins-bad/ext/webrtc/transportsendbin.c:346):transport_send_bin_constructed: code should not be reached

** (gst-launch-1.0:6049): CRITICAL **: 19:13:28.841: gst_dtls_srtp_enc_request_new_pad: assertion 'self->srtp_enc' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:6049): CRITICAL **: 19:13:28.841: gst_dtls_srtp_enc_request_new_pad: assertion 'self->srtp_enc' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:6049): CRITICAL **: 19:13:28.841: gst_dtls_srtp_enc_request_new_pad: assertion 'self->srtp_enc' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.841: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:6049): WARNING **: 19:13:28.842: (../subprojects/gst-plugins-bad/ext/webrtc/transportreceivebin.c:348):transport_receive_bin_constructed: code should not be reached

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:6049): CRITICAL **: 19:13:28.842: gst_dtls_srtp_dec_request_new_pad: assertion 'self->bin.dtls_element' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.842: gst_object_unref: assertion 'object != NULL' failed

** (gst-launch-1.0:6049): WARNING **: 19:13:28.842: (../subprojects/gst-plugins-bad/ext/webrtc/gstwebrtcbin.c:2251):_create_transport_channel: code should not be reached

** (gst-launch-1.0:6049): WARNING **: 19:13:28.843: (../subprojects/gst-plugins-bad/ext/webrtc/gstwebrtcbin.c:2257):_create_transport_channel: code should not be reached

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_pad_get_peer: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_ref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_pad_add_probe: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_pad_get_peer: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_ref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_pad_add_probe: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_pad_get_peer: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_ref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_pad_add_probe: assertion 'GST_IS_PAD (pad)' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.843: gst_object_unref: assertion 'object != NULL' failed
0:00:18.872285076  6049 0x7f7b48007d80 WARN                GST_PADS gstpad.c:4351:gst_pad_peer_query:<nicesrc0:src> could not send sticky events
0:00:18.872384121  6049 0x7f7b480076a0 WARN             dtlssrtpdec gstdtlssrtpdec.c:282:gst_dtls_srtp_dec_get_property:<dtlssrtpdec0> tried to get pem after disabling DTLS

** (gst-launch-1.0:6049): CRITICAL **: 19:13:28.843: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed
0:00:18.872519872  6049 0x7f7b480076a0 WARN             dtlssrtpdec gstdtlssrtpdec.c:282:gst_dtls_srtp_dec_get_property:<dtlssrtpdec0> tried to get pem after disabling DTLS

** (gst-launch-1.0:6049): CRITICAL **: 19:13:28.843: _generate_fingerprint_from_certificate: assertion 'certificate != NULL' failed
2022-01-27 19:13:28,865 - webrtc.signalling - INFO - Connection to peer ('10.18.27.150', 59936) closed, exiting handler
2022-01-27 19:13:28,866 - webrtc.signalling - INFO - Cleaned up 79c2b726-8117-4e6e-9113-4ffcd36d5749 -> c96f5450-6ebf-48fc-a5a7-7aebec485ee6 session
2022-01-27 19:13:28,866 - webrtc.signalling - INFO - Disconnected from peer '79c2b726-8117-4e6e-9113-4ffcd36d5749' at ('10.18.27.150', 59936)

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.867: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.867: gst_object_unref: assertion 'object != NULL' failed

(gst-launch-1.0:6049): GStreamer-CRITICAL **: 19:13:28.867: gst_object_unref: assertion 'object != NULL' failed
```

**Comment by JBG-brad** [comment]
User error.  I didn't have libsrtp-dev installed, but it failed silently installed the plugin.

Installing the package and then changing the meson build flags to:

`meson -Dbad=enabled -Dgst-plugins-bad:srtp=enabled build`

Enabled srtp and failed the build if libsrtp-dev wasn't installed.

**Comment by MathieuDuponchelle** [comment]
Ah, good, would be better if things didn't explode that way though, if you care to dig deeper and make the underlying code error out properly :)
