### ISSUE TITLE
panic when client tries to connect

### ISSUE THREAD

**Issue by joaoantoniocardoso** [centricular/webrtcsink#33]
Hi, I was running webrtcsink pipelines with no major issues, but since the bd560fa9f96968d31215e0d0c173be7da856c8fd I am getting a panic from webrtcsink.

I can still create my pipeline and run it, but when my client (browser) tries to connect, I got the following output on the terminal that is running the pipeline:

```
RUST_BACKTRACE=1 GST_PLUGIN_PATH=/home/myuser/BlueRobotics/webrtcsink/target/debug:$GST_PLUGIN_PATH gst-launch-1.0 videotestsrc pattern=ball ! video/x-raw,width=640,height=480,framerate=5/1 ! videoconvert ! webrtcsink stun-server=stun://0.0.0.0:3478 turn-server=turn://test:test123@0.0.0.0:3478 video-caps=video/x-h264,width=640,height=480,framerate=5/1

Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "property 'msid-appdata' of type 'WebRTCTransceiver' not found", filename: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.9/src/object.rs", function: "glib::object", line: 2164 }', /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.9/src/object.rs:2186:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: <T as glib::object::ObjectExt>::set_property
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.9/src/object.rs:2186:9
   5: webrtcsink::webrtcsink::imp::Consumer::request_webrtcbin_pad
             at /home/myuser/BlueRobotics/webrtcsink/plugins/src/webrtcsink/imp.rs:1001:9
   6: webrtcsink::webrtcsink::imp::WebRTCSink::add_consumer::{{closure}}
             at /home/myuser/BlueRobotics/webrtcsink/plugins/src/webrtcsink/imp.rs:1654:37
   7: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/iter/traits/iterator.rs:734:29
   8: core::iter::traits::iterator::Iterator::fold
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/iter/traits/iterator.rs:2171:21
   9: core::iter::traits::iterator::Iterator::for_each
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/iter/traits/iterator.rs:737:9
  10: webrtcsink::webrtcsink::imp::WebRTCSink::add_consumer
             at /home/myuser/BlueRobotics/webrtcsink/plugins/src/webrtcsink/imp.rs:1651:9
  11: webrtcsink::webrtcsink::WebRTCSink::add_consumer
             at /home/myuser/BlueRobotics/webrtcsink/plugins/src/webrtcsink/mod.rs:121:9
  12: webrtcsink::signaller::imp::Signaller::connect::{{closure}}::{{closure}}
             at /home/myuser/BlueRobotics/webrtcsink/plugins/src/signaller/imp.rs:120:59
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  14: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.10.0/src/task/builder.rs:199:17
  15: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.10.0/src/task/task_locals_wrapper.rs:60:13
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
  18: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.10.0/src/task/task_locals_wrapper.rs:55:9
  19: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.10.0/src/task/builder.rs:197:13
  20: async_executor::Executor::spawn::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:144:13
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  22: async_task::raw::RawTask<F,T,S>::run
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.2.0/src/raw.rs:489:20
  23: async_task::runnable::Runnable::run
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.2.0/src/runnable.rs:309:18
  24: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:235:21
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  26: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:529:33
  27: async_executor::Executor::run::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:242:9
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  29: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:529:33
  30: async_io::driver::block_on
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.6.0/src/driver.rs:142:33
  31: async_global_executor::reactor::block_on::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.3/src/reactor.rs:3:18
  32: async_global_executor::reactor::block_on
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.3/src/reactor.rs:12:5
  33: async_global_executor::threading::thread_main_loop::{{closure}}::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.3/src/threading.rs:95:17
  34: std::thread::local::LocalKey<T>::try_with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
  35: std::thread::local::LocalKey<T>::with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
  36: async_global_executor::threading::thread_main_loop::{{closure}}
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.3/src/threading.rs:89:13
  37: std::panicking::try::do_call
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  38: __rust_try
  39: std::panicking::try
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  40: std::panic::catch_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  41: async_global_executor::threading::thread_main_loop
             at /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.3/src/threading.rs:88:12
  42: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I tested it using both [coturn](https://github.com/coturn/coturn) and [webrtc-rs/turn](https://github.com/webrtc-rs/turn), and the web client side is the www provided in this repository.

Let me know if this is a problem with my setupo or if any other information is needed to investigate it further.

Thank you

**Comment by joaoantoniocardoso** [comment]
Oh sure, I am running it with GStreamer 1.20.1-1. I'll be glad if you could make that compatible with the previous versions :)
thanks

**Comment by MathieuDuponchelle** [comment]
Ah, yes, should be easy to solve indeed. In my defense the README still states "GStreamer main" :P

**Comment by MathieuDuponchelle** [comment]
hrm, I didn't actually get https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2003 merged yet, so my last line of defense sort of crumbles

**Comment by MathieuDuponchelle** [comment]
Fixed, sorry for the mess :)

**Comment by joaoantoniocardoso** [comment]
I can confirm the panic is solved. Thank you!
