### ISSUE TITLE
Built Rust code fails when trying to use webrtcbin pad but gst-inspect can find the plugin

### ISSUE THREAD

**Issue by colemickens** [centricular/webrtcsink#68]
Hi,

I've got a nix-shell with gstreamer plugins available. I'm able to get this code to build, but as soon as a consumer is added, the gst-launch pipeline that is producing video, fails inside webrtcsink code:

```
thread 'async-std/runtime' panicked at 'called `Option::unwrap()` on a `None` value', plugins/src/webrtcsink/imp.rs:1201:14
```

It seems like this is because it's unable to create a webrtcbin pad. But I'm not sure why. In the same nix-shell I can run:

```
[cole@slynux:~/code/webrtcsink]$ gst-inspect-1.0 webrtcbinFactory Details:
  Rank                     primary (256)
  Long-name                WebRTC Bin
  Klass                    Filter/Network/WebRTC
  Description              A bin for webrtc connections
  Author                   Matthew Waters <matthew@centricular.com>

Plugin Details:
  Name                     webrtc
  Description              WebRTC plugins
  Filename                 /nix/store/81afg749765nad7xl53s9qsmvxr0sdzx-gst-plugins-bad-1.20.1/lib/gstreamer-1.0/libgstwebrtc.so
  Version                  1.20.1
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2022-03-14
  Binary package           GStreamer Bad Plug-ins source release
  Origin URL               Unknown package origin

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBin
                         +----GstWebRTCBin

Implemented Interfaces:
  GstChildProxy

Pad Templates:
  SINK template: 'sink_%u'
    Availability: On request
    Capabilities:
      application/x-rtp
    Type: GstWebRTCBinPad
    Pad Properties:
      transceiver         : Transceiver associated with this pad
                            flags: readable

```

Any hints?r

**Comment by sdroege** [comment]
Can you get a debug log with `GST_DEBUG=6`?

**Comment by RustPanda** [comment]
On fedora 36, the plugin returns the same error

**Comment by RustPanda** [comment]
> В Fedora 36 плагин возвращает ту же ошибку.

```sh
gst-launch-1.0  webrtcsink name=ws videotestsrc  ! ws. audiotestsrc ! ws. 
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
Redistribute latency...
thread 'async-std/runtime' panicked at 'called `Option::unwrap()` on a `None` value', plugins/src/webrtcsink/imp.rs:1201:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
0:00:10.9 / 99:99:99.
```

**Comment by MathieuDuponchelle** [comment]
Feel free to propose a patch to avoid panicking in that situation btw :)

**Comment by RustPanda** [comment]
`$ sudo dnf install libnice-gstreamer1`

**Comment by MathieuDuponchelle** [comment]
Closing, this seems resolved
