### ISSUE TITLE
Signal 'request-aux-sender' of type 'GstWebRTCBin' not found

### ISSUE THREAD

**Issue by mattfeury** [centricular/webrtcsink#88]
Hello,

Love the plugin from what I'm seeing! I'm trying to get it running but encountering this error when a client connects:

```
Signal 'request-aux-sender' of type 'GstWebRTCBin' not found
```

I can see [here](https://github.com/centricular/webrtcsink/blob/2dc42ba0db1efee376ace7d8d7a7adecede47a0a/plugins/src/webrtcsink/imp.rs#L1352) that we connect a "request-aux-sender" signal handler to the webrtc element, which is where the issue is likely happening. 

looking into it a bit, i see that signal defined on [rtpbin](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-rtpbin.html#GstRtpBin-request-aux-sender), but not on [webrtcbin](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-webrtcbin.html#gst-plugins-bad-plugins-webrtcbin.signals). hoping you can shed some light on this. thanks!

running on a mac

logs:
```
> RUST_BACKTRACE=1 GST_DEBUG=3 gst-launch-1.0 webrtcsink name=ws videotestsrc ! ws. audiotestsrc ! ws.
0:00:00.039141000   469 0x7fa0551b6160 WARN      GST_PLUGIN_LOADING gstplugin.c:509:gst_plugin_register_func: plugin "/Users/home/webrtcsink/target/debug/libwebrtcsink.dylib" has unknown license "MIT"
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
0:00:00.061398000   469 0x7fa05600b180 FIXME                default gstutils.c:4026:gst_pad_create_stream_id_internal:<videotestsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:00.061400000   469 0x7fa05600b1e0 FIXME                default gstutils.c:4026:gst_pad_create_stream_id_internal:<audiotestsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
Redistribute latency...
0:00:00.084205000   469 0x7fa05600b2a0 FIXME                default gstutils.c:4026:gst_pad_create_stream_id_internal:<audiotestsrc1:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:00.086536000   469 0x7fa05600b2a0 WARN         audio-resampler audio-resampler.c:274:convert_taps_gint16_c: can't find exact taps
0:00:00.101999000   469 0x7fa05600b300 FIXME                default gstutils.c:4026:gst_pad_create_stream_id_internal:<videotestsrc1:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:00.122054000   469 0x7fa05600b360 FIXME                default gstutils.c:4026:gst_pad_create_stream_id_internal:<videotestsrc2:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:00.131033000   469 0x7fa05480ec00 FIXME                default gstutils.c:4026:gst_pad_create_stream_id_internal:<videotestsrc3:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:00.147731000   469 0x7fa05480ec00 WARN                  vpxenc gstvpxenc.c:1862:gst_vpx_enc_set_format:<vp9enc0> Failed to set VP8E_SET_NOISE_SENSITIVITY: incapable
0:00:00.147951000   469 0x7fa05480ec00 WARN                  vpxenc gstvpxenc.c:1882:gst_vpx_enc_set_format:<vp9enc0> Failed to set VP8E_SET_TOKEN_PARTIONS: incapable
0:00:00.287112000   469 0x7fa05600b360 WARN                   vtenc vtenc.c:1056:gst_vtenc_set_colorimetry:<vtenc_h264-0> Unsupported color matrix 1
0:00:00.315911000   469 0x7fa05600b360 ERROR           videoencoder gstvideoencoder.c:2280:gst_video_encoder_can_push_unlocked:<vtenc_h264-0> Output state was not configured
0:00:00.315940000   469 0x7fa05600b360 WARN            videoencoder gstvideoencoder.c:2282:gst_video_encoder_can_push_unlocked:<vtenc_h264-0> error: Output state was not configured
0:00:00.320353000   469 0x7fa0554106c0 WARN              webrtcsink plugins/src/webrtcsink/imp.rs:2082:webrtcsink::webrtcsink::imp:<ws> Codec discovery pipeline failed: Output state was not configured
thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Signal 'request-aux-sender' of type 'GstWebRTCBin' not found", filename: "/Users/home/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/4ca23ca/glib/src/object.rs", function: "glib::object", line: 2868 }', /Users/home/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/4ca23ca/glib/src/object.rs:2879:14
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/result.rs:1098:23
   4: <T as glib::object::ObjectExt>::connect_closure
             at /Users/home/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/4ca23ca/glib/src/object.rs:2878:9
   5: webrtcsink::webrtcsink::imp::WebRTCSink::add_consumer
             at ./plugins/src/webrtcsink/imp.rs:1351:17
   6: webrtcsink::webrtcsink::WebRTCSink::add_consumer
             at ./plugins/src/webrtcsink/mod.rs:121:9
   7: webrtcsink::signaller::imp::Signaller::connect::{{closure}}::{{closure}}
             at ./plugins/src/signaller/imp.rs:137:59
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/future/mod.rs:91:19
   9: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:199:17
  10: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/task_locals_wrapper.rs:60:13
  11: std::thread::local::LocalKey<T>::try_with
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/std/src/thread/local.rs:445:16
  12: std::thread::local::LocalKey<T>::with
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/std/src/thread/local.rs:421:9
  13: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/task_locals_wrapper.rs:55:9
  14: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:197:13
  15: async_executor::Executor::spawn::{{closure}}
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:144:19
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/future/mod.rs:91:19
  17: async_task::raw::RawTask<F,T,S>::run
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/raw.rs:511:20
  18: async_task::runnable::Runnable::run
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/runnable.rs:309:18
  19: async_executor::Executor::run::{{closure}}::{{closure}}
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:235:21
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/future/mod.rs:91:19
  21: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:529:33
  22: async_executor::Executor::run::{{closure}}
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:242:31
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/future/mod.rs:91:19
  24: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:529:33
  25: async_io::driver::block_on
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.8.0/src/driver.rs:142:33
  26: async_global_executor::reactor::block_on::{{closure}}
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.2.0/src/reactor.rs:3:18
  27: async_global_executor::reactor::block_on
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.2.0/src/reactor.rs:12:5
  28: async_global_executor::threading::thread_main_loop::{{closure}}::{{closure}}
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.2.0/src/threading.rs:95:17
  29: std::thread::local::LocalKey<T>::try_with
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/std/src/thread/local.rs:445:16
  30: std::thread::local::LocalKey<T>::with
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/std/src/thread/local.rs:421:9
  31: async_global_executor::threading::thread_main_loop::{{closure}}
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.2.0/src/threading.rs:89:13
  32: std::panicking::try::do_call
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/std/src/panicking.rs:492:40
  33: ___rust_try
  34: std::panicking::try
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/std/src/panicking.rs:456:19
  35: std::panic::catch_unwind
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/std/src/panic.rs:137:14
  36: async_global_executor::threading::thread_main_loop
             at /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.2.0/src/threading.rs:88:12
  37: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
0:00:06.7 / 99:99:99.
0:00:06.9 / 99:99:99.
```

**Comment by colemickens** [comment]
I hit this recently, did some digging and it seems that this plugin relies on the unreleased tip of gstreamer tree. Until the next release, presumably?

(I happen to have a nix development environment defined with a recent tip of gstreamer that allows the plugin to build again: `nix develop github:colemickens/nixcfg#gstreamer`.)

**Comment by colemickens** [comment]
I think this is the relevant commit: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/073df3d82094be9c8ed397f9e96146d9a205d0f9

**Comment by rbdm** [comment]
I also stumbled upon this issue today.

for me it is working when I switched to colemickens' dev environment - thanks :+1:

**Comment by MathieuDuponchelle** [comment]
Hey folks, thanks for being this reactive, I was away for a short vacation :)

Yes, in general, you should consider that when updating to the latest version of `webrtcsink`, you will probably want to also run against gstreamer main. This could be better advertised either through branches or tags, but as the short / mid term plan is to get this merged in `gst-plugins-rs` I'd rather not sink time into figuring out a solution that will be obsoleted immediately.

Closing as @mattfeury's issue will be solved by updating to latest gst main.

**Comment by MathieuDuponchelle** [comment]
btw, the "portable/official" method for running latest gst is described in its README: https://gitlab.freedesktop.org/gstreamer/gstreamer/ , though that nix thing seems nice :)
