### ISSUE TITLE
The stream doesn't start in chrome

### ISSUE THREAD

**Issue by mikolajkniejski** [centricular/webrtcsink#94]
# Summary
It's impossible to start the stream in Chrome.

# Steps to reproduce
Clone https://github.com/centricular/webrtcsink to workspace and follow the steps in README using a Chrome browser. 

# What is the current bug behavior?
After clicking the button to start the stream the browser throws an error and the stream doesn't start.

# What is the expected correct behavior?
The stream starts.

# Relevant logs and/or screenshots
```
Received {"type":"peer","peerId":"7527b980-14de-44e4-8a71-1428d630d5cc","sdp":{"type":"offer","sdp":"v=0\r\no=- 7037386473251720009 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=ice-options:trickle\r\na=group:BUNDLE video0 audio1\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 96 96 96 96\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:ADrxWPMUIOOTDlIK1R6v2B9C1LzzzgTP\r\na=ice-pwd:cdXE0YqMBw9/ORc7asCpWJKtXnGG7QDz\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendonly\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 transport-cc\r\na=extmap:1 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=rtpmap:97 H264/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 transport-cc\r\na=fmtp:97 packetization-mode=1;profile-level-id=42c00d;level-asymmetry-allowed=1\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:98 transport-cc\r\na=rtpmap:99 H265/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 transport-cc\r\na=fmtp:99 sprop-vps=QAEMAf//AUAAAAMAAAMAAAMAAAMAPKwJ;sprop-sps=QgEBAUAAAAMAAAMAAAMAAAMAPKAKCAQHxOWtKQlkuMBbgIaAAgAAAwACAAADADwQ;sprop-pps=RAHA98DMkA==\r\na=rtpmap:96 red/90000\r\na=rtpmap:96 ulpfec/90000\r\na=rtpmap:96 rtx/90000\r\na=fmtp:96 apt=96\r\na=rtpmap:96 rtx/90000\r\na=fmtp:96 apt=96\r\na=ssrc-group:FID 2562101142 2681033657\r\na=ssrc:2562101142 msid:user1635216468@host-5482cbee webrtctransceiver10\r\na=ssrc:2562101142 cname:user1635216468@host-5482cbee\r\na=ssrc:2562101142 msid:user1635216468@host-5482cbee webrtctransceiver10\r\na=ssrc:2562101142 cname:user1635216468@host-5482cbee\r\na=ssrc:2562101142 msid:user1635216468@host-5482cbee webrtctransceiver10\r\na=ssrc:2562101142 cname:user1635216468@host-5482cbee\r\na=ssrc:2562101142 msid:user1635216468@host-5482cbee webrtctransceiver10\r\na=ssrc:2562101142 cname:user1635216468@host-5482cbee\r\na=ssrc:2681033657 msid:user1635216468@host-5482cbee webrtctransceiver10\r\na=ssrc:2681033657 cname:user1635216468@host-5482cbee\r\na=mid:video0\r\na=fingerprint:sha-256 C6:35:80:D0:56:8D:ED:D6:1F:ED:82:31:A2:51:64:9F:47:02:8F:22:5A:F0:18:35:C7:70:6D:C5:78:0B:CB:06\r\na=rtcp-mux-only\r\nm=audio 0 UDP/TLS/RTP/SAVPF 100\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:ADrxWPMUIOOTDlIK1R6v2B9C1LzzzgTP\r\na=ice-pwd:cdXE0YqMBw9/ORc7asCpWJKtXnGG7QDz\r\na=bundle-only\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=sendonly\r\na=rtpmap:100 OPUS/48000/2\r\na=rtcp-fb:100 transport-cc\r\na=extmap:1 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=fmtp:100 sprop-stereo=0;sprop-maxcapturerate=48000\r\na=ssrc:624556132 msid:user1635216468@host-5482cbee webrtctransceiver11\r\na=ssrc:624556132 cname:user1635216468@host-5482cbee\r\na=mid:audio1\r\na=fingerprint:sha-256 C6:35:80:D0:56:8D:ED:D6:1F:ED:82:31:A2:51:64:9F:47:02:8F:22:5A:F0:18:35:C7:70:6D:C5:78:0B:CB:06\r\na=rtcp-mux-only\r\n"}}
webrtc.js:255 Creating RTCPeerConnection
webrtc.js:92 Created peer connection for call, waiting for SDP
webrtc.js:100 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=rtpmap:96 red/90000 Duplicate  payload type with conflicting codec name or clock rate.
    at RTCPeerConnection.setRemoteDescription (https://webrtc.github.io/adapter/adapter-latest.js:1421:37)
    at Session.onIncomingSDP (http://localhost:8080/webrtc.js:135:30)
    at Session.onServerMessage (http://localhost:8080/webrtc.js:178:22)
```
# Desktop
OS: Linux x86_64
Pop_os

Browser: Version 104.0.5112.101 (Official Build) (64-bit) 
(a .deb package downloaded from chrome website)

**Comment by mikolajkniejski** [comment]
@MathieuDuponchelle

**Comment by MathieuDuponchelle** [comment]
Thanks for the report, I can reproduce the issue, the proposed fix is at https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2984

**Comment by MathieuDuponchelle** [comment]
I'll close this once the MR has landed :)

**Comment by MathieuDuponchelle** [comment]
It has, closing, thanks for the report!
